# Generated by Django 4.2.6 on 2023-12-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookinfo_options_peopleinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleinfo',
            name='gender',
            field=models.SmallIntegerField(choices=[(2, 'female'), (1, 'male')], default=1),
        ),
    ]
