# Generated by Django 4.2.6 on 2023-12-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_peopleinfo_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'verbose_name': '图书'},
        ),
        migrations.RenameField(
            model_name='peopleinfo',
            old_name='descriptioin',
            new_name='description',
        ),
    ]
